server:
  port: 0

spring:
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name:
      profile:
  management:
    endpoints:
      web:
        exposure:
          include:
  redis:
    host: ENC(yha6a9F8LiwHb6JXePz6nZmlX8CH1sOYb4dIpyVAZjZLFJEBtXpm0vj36Jf6icBCBL6try2afbp/MqeFOd1UWQ==)
    password: ENC(wnaFaxnI5HNitC+hmbvdJ51kAuc7D6i4)
    port: 6379
  session:
    store-type: redis
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  expiration_time: 86400000
  secret: user_token

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
