server:
  port: 0

spring:
  # config server 정보
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: config
      profile: dev
  management:
    endpoints:
      web:
        exposure:
          include:
  session:
    store-type: redis
  application:
    name: board-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: C:\GITSERK

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
