server:
  port: 8000

spring:
  # config server 정보
  config:
    import: "optional:configserver:http://localhost:8888/"
  application:
    name: apigateway-service
  cloud:
    config:
      name: config
      profile: dev
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
  management:
    endpoints:
      web:
        exposure:
          include:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
